version: '3.8'
services:
  nginx:
    build: .
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - www:/data/www
    networks:
      - default
volumes:
  www:
    external: false
networks:
  default:
    driver: bridge
    external:
      name: ${DEFAULT_NETWORK_NAME:-opex}