version: '3.8'
services:
  nginx:
    build: .
    volumes:
      - www:/data/www
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  www:
    external: false
networks:
  default:
    driver: bridge
    name: ${DEFAULT_NETWORK_NAME:-opex}